version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Snowflake.API/Dockerfile
    ports:
      - "8000:80"
    networks:
      - webnet
  test:
    image: ${DOCKER_REGISTRY-}test
    build:
      context: .
      dockerfile: Snowflake.Test/Dockerfile
    networks:
      - webnet
    depends_on:
      - api
networks:
  webnet:
    external: true